# Generated by Django 6.1 on 2026-08-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_app', '0003_otpcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpcode',
            name='payload',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='purpose',
            field=models.CharField(choices=[('REGISTER', 'Inscription'), ('LOGIN', 'Connexion'), ('PROFILE', 'Modification profil')], max_length=10),
        ),
    ]
