# Generated by Django 6.1 on 2026-08-19 11:03

import tickets_app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_app', '0004_otpcode_payload_alter_otpcode_purpose'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', tickets_app.models.CustomUserManager()),
            ],
        ),
    ]
