# Generated by Django 6.1 on 2026-08-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_app', '0006_user_failed_login_attempts_user_locked_until_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lockout_duration_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
